version: '3'
services:
  app:
    image: node:13
    volumes:
      - ./bluestone-app:/usr/src/service
    working_dir: /usr/src/service
    command: bash -c "npm install && npm start"
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
  nginx:
    image: nginx:alpine
    restart: always
  proxy:
    build: ./nginx
    ports:
      - 8080:8080
    restart: always